# ./k8s/api/pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: video-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/k8s/videos
