apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api-service-account  # ✅ Assign the Service Account
      containers:
        - name: api
          image: orsi-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: UPLOAD_FOLDER
              value: "/data/videos"
            - name: CORS_ORIGINS
              value: "http://172.19.245.152:30001"
          volumeMounts:
            - mountPath: /data/videos
              name: video-storage
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: video-pvc
